debug: false
---
spring:
 profiles: development
 main:
  banner-mode: "off"
 application:
  name: secure-ms-sample-provider
#security:
#  user:
#    name: admin
#    password: secret
management:
  context-path: /actuator
  security:
    roles: ACTUATOR
#    enabled: false
server:
#  servlet-path: /api

springfox.documentation.swagger.v2:
  path: /api-docs
demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  tokenIssuer: ${spring.application.name:jce-demo-secure-mvn1}
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
---  
spring:
 profiles: cloud
 main:
  banner-mode: "off" 
 application:
  name: ${vcap.application.application_name:secure-ms-sample-provider}
#security:
#  user:
#    name: admin
#    password: secret
management:
  context-path: /actuator
  security:
    roles: ACTUATOR
#    enabled: false
#server:
#  servlet-path: /api
springfox.documentation.swagger.v2:
  path: /api-docs
demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  tokenIssuer: ${spring.application.name:jce-demo-secure-mvn1}
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
