debug: false
---
spring:
 profiles: development
 main:
  banner-mode: "off"
 application:
  name: bff1-jp-secure-ms
#security:
#  user:
#    name: admin
#    password: secret
microservice:
  endpoint:
    ms1: http://ms1-jp-secure-ms.mybluemix.net
    ms2: http://ms2-jp-secure-ms.mybluemix.net
management:
  context-path: /actuator
  security:
    roles: ACTUATOR
#    enabled: false
server:
#  servlet-path: /api

springfox.documentation.swagger.v2:
  path: /api-docs
demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  tokenIssuer: ${spring.application.name:bff1-jp-secure-ms}
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
---  
spring:
 profiles: cloud
 main:
  banner-mode: "off" 
 application:
  name: ${vcap.application.application_name:bff1-jp-secure-ms}
#security:
#  user:
#    name: admin
#    password: secret
management:
  context-path: /actuator
  security:
    roles: ACTUATOR
#    enabled: false
#server:
#  servlet-path: /api
springfox.documentation.swagger.v2:
  path: /api-docs
demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  tokenIssuer: ${spring.application.name:bff1-jp-secure-ms}
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
microservice:
  endpoint:
    ms1: https://ms1-jp-secure-ms.mybluemix.net
    ms2: https://ms2-jp-secure-ms.mybluemix.net
#    ms1: https://secure-ms-sample-provider.itdept.charlesedw.com
